### ISSUE TITLE
could you share your pretrained models?

### ISSUE THREAD

**Issue by dnrtn1101** [JasonBoy1/TextZoom#25]
Or is it shared somewhere like a google drive?

**Comment by JasonBoy1** [comment]
A buddy uploaded the best model weights after 42000 epochs of training on TextZoom data:
https://drive.google.com/file/d/1j-g17V5kBmqS8giWNZuHe2d_GefAepCs/view?usp=sharing

**Comment by lmmx** [comment]
Giving an error for me unfortunately

```py
loading pre-trained model from ../models/textzoom.pth
Traceback (most recent call last):
File "main.py", line 44, in <module>
main(config, args)
File "main.py", line 16, in main
Mission.demo()
File "/home/louis/dev/sr/TextZoom/src/interfaces/super_resolution.py", line 276, in demo
model_dict = self.generator_init()
File "/home/louis/dev/sr/TextZoom/src/interfaces/base.py", line 158, in generator_init
model.load_state_dict(torch.load(self.resume)['state_dict_G'])
File "/home/louis/miniconda3/envs/textzoom/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
Missing key(s) in state_dict: "module.block1.0.weight", "module.block1.0.bias", "module.block1.1.weight",
"module.block2.conv1.weight", "module.block2.conv1.bias",
```

Thanks for sharing anyway :+1:
