### ISSUE TITLE
Invalid device ID with demo test

### ISSUE THREAD

**Issue by nahidalam** [JasonBoy1/TextZoom#39]
I am trying to test this using the pretrained model and getting below error. Testing this in a system that has 1 GPU

```Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main(config, args)
  File "main.py", line 16, in main
    Mission.demo()
  File "/root/TextZoom/src/interfaces/super_resolution.py", line 276, in demo
    model_dict = self.generator_init()
  File "/root/TextZoom/src/interfaces/base.py", line 153, in generator_init
    model = torch.nn.DataParallel(model, device_ids=range(cfg.ngpu))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 136, in __init__
    _check_balance(self.device_ids)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 317, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

I used this command
```
python3 main.py --demo --demo_dir='./images/' --resume='your-model.pth' --STN --mask
```
And used the pretrained model you mentioned [here](https://github.com/JasonBoy1/TextZoom/issues/8)

**Comment by nahidalam** [comment]
This particular issue is resolved with [28](https://github.com/JasonBoy1/TextZoom/issues/28)
